### ISSUE TITLE
change [self addObservers] location

### ISSUE THREAD

**Issue by vbapst** [ihomam/CollectionViewWithSearchBar#4]
I think that [self addObservers] should be located in the init function and not in viewDidAppear (unless there is a reason not to ?).

This makes a difference once you use this controller in a hierarchy :  if you allow the controller to pop another view and then come back to it (so that ViewDidAppear is called several times). Then you get a memory crash when exiting the collection view controller. The small change I propose seems to solve this problem.

Apart from that that's a great piece of code.

**Comment by ihomam** [comment]
thanx vbapst :) you're totally right. 
I faced the bug in a project that i had built and fixed it. Forgot to update the code here :s 

i think it's better to put it in addSearchBar method, inside if (!self.searchBar) statement. then we can be sure that Observer is gonna be added only one time.

putting [self addObservers] in 
- (instancetype)initWithCoder:(NSCoder *)aDecoder
  would make a crash with a msg NSInternalInconsistencyException, i think it happens because the view is not ready yet 

what do you think ?!

**Comment by vbapst** [comment]
In my case I put it inside the init as follows :
- (instancetype) initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil
  {
  self = [ super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
  if (self) {
      [self addObservers];
   }
  return self;  
  }

and this (seems to) work. But what you suggest would also work (I first used this kind of fix with a global boolean set to true in the init and to false once you add the observer). I think you are more advanced than me and you will make a better decision ;-)

**Comment by ihomam** [comment]
I went through crazy days :s 
managed today to update the code. thanx vbapst  ^_^
